# Generated by Django 2.1.7 on 2019-03-09 06:46

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(blank=True, max_length=140, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(blank=True, max_length=140, null=True)),
                ('popularity_99', models.DecimalField(decimal_places=2, default=10, max_digits=4)),
                ('director', models.CharField(blank=True, max_length=100, null=True)),
                ('imdb_score', models.DecimalField(decimal_places=2, default=10, max_digits=4)),
                ('genre', models.ManyToManyField(blank=True, null=True, to='movie_app.MovieGenre')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
