# Generated by Django 2.1.7 on 2019-03-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, related_name='get_movie_genre', to='movie_app.MovieGenre'),
        ),
    ]
